In [2]:
import pandas as pd

df = pd.read_csv("output\output_analyzed_df.csv")

In [3]:
df

,title,link,content,date,source,clean_content,domain,summary,keywords,cluster
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,2025-03-01 00:00:00,KPMG,india cx report commercial real estate close c...,Energy,Back industries aerospace defence space energ...,"['leasing', 'redevelopment', 'renovations', 'w...",2
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,2025-03-01 00:00:00,KPMG,india cx report residential real estate close ...,Energy,Back industries aerospace defence space energ...,"['residential', 'amenities', 'luxury', 'builde...",2
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,2025-03-01 00:00:00,KPMG,india cx report real estate close contactmail ...,Technology,Back industries aerospace defence space energ...,"['innovate', 'renewables', 'industries', 'expl...",2
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,2025-03-01 00:00:00,KPMG,india cx report premium hotels close contactma...,Energy,Back industries aerospace defence space energ...,"['hotels', 'hotel', 'hotelchain', 'resorts', '...",2
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,2025-03-01 00:00:00,KPMG,india cx report hotels close contactmail conta...,Technology,Back industries aerospace defence space energ...,"['hoteliers', 'hotels', 'hotel', 'establishmen...",2
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,2025-03-01 00:00:00,KPMG,india cx report budget hotels close contactmai...,Energy,Back industries aerospace defence space energ...,"['hotels', 'hotel', 'hotelchain', 'facilities'...",2
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,2025-03-01 00:00:00,KPMG,india cx report consumer durables close contac...,Technology,Back industries aerospace defence space energ...,"['appliances', 'consumer', 'industries', 'rene...",2
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,2025-03-01 00:00:00,KPMG,india cx report small appliances close contact...,Technology,Back industries aerospace defence space energ...,"['appliances', 'appliance', 'electrical', 'ren...",2
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,2025-03-01 00:00:00,KPMG,india cx report large appliances close contact...,Technology,Back industries aerospace defence space energ...,"['appliances', 'appliance', 'electrical', 'ren...",2
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,2025-03-01 00:00:00,KPMG,evolving third party landscape indias media en...,Technology,Back industries aerospace defence space energ...,"['sector', 'emerging', 'indias', 'industries',...",2
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,2025-03-01 00:00:00,KPMG,issue march close contactmail contact us india...,Technology,kpmg learning academy board leadership transf...,"['logistics', 'sector', 'consulting', 'acquisi...",5
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,2025-03-01 00:00:00,KPMG,related party transactions – minimum informati...,Technology,Back industries aerospace defence space energ...,"['industries', 'industry', 'securities', 'logi...",2
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,2025-03-01 00:00:00,KPMG,thirdparty risks pharmaceutical supply chain c...,Energy,Back industries aerospace defence space energ...,"['pharmaceuticals', 'risks', 'pharmaceutical',...",0
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,2025-03-01 00:00:00,KPMG,intelligent retail close contactmail contact u...,Technology,Back industries aerospace defence space energ...,"['retail', 'sector', 'industries', 'sectorwide...",2
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,2025-03-01 00:00:00,KPMG,india ’ digital transformation provides bluepr...,Technology,india ’ digital transformation provides bluep...,"['digitalisation', 'revolutionize', 'advanceme...",2
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,2025-03-01 00:00:00,KPMG,cybersecurity considerations close contactmail...,Technology,Back industries aerospace defence space energ...,"['cybersecurity', 'cyber', 'increasingly', 'se...",2
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG,india cx report airlines close contactmail con...,Technology,Back industries aerospace defence space energ...,"['airlines', 'airline', 'postflight', 'aviatio...",2
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,2025-03-01 00:00:00,KPMG,mastering intentional experiences india cx rep...,Technology,Back industries aerospace defence space energ...,"['engendering', 'innovation', 'experienced', '...",2
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,2025-03-01 00:00:00,KPMG,navigating reserve bank india ’ guidelines nef...,Technology,navigating reserve bank india ’ guidelines ne...,"['reserve', 'neft', 'bank', 'regulation', 'reg...",5
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",2025-03-01 00:00:00,KPMG,indian ports better ’ next close contactmail c...,Technology,Back industries aerospace defence space energ...,"['ports', 'port', 'shipbuilding', 'waterways',...",6
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,2025-03-01 00:00:00,KPMG,innovative strategies cost optimisation – need...,Technology,Back industries aerospace defence space energ...,"['strategies', 'cement', 'innovative', 'strate...",2
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG,india cx report airlines close contactmail con...,Technology,Back industries aerospace defence space energ...,"['airlines', 'airline', 'postflight', 'aviatio...",2
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,2025-03-01 00:00:00,KPMG,pulse fintech h close contactmail contact us i...,Technology,pulse fintech h close contactmail contact us ...,"['fintech', 'wealthtech', 'industries', 'trend...",2
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,2025-03-01 00:00:00,KPMG,rise silver generation transforming senior liv...,Technology,Back industries aerospace defence space energ...,"['seniors', 'senior', 'aging', 'renewables', '...",1
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,2025-03-01 00:00:00,KPMG,aviation leasing financing ecosystem gift ifsc...,Technology,Aviation leasing financing ecosystem gift ifs...,"['airlines', 'leasing', 'airline', 'aviation',...",2
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,2025-03-01 00:00:00,KPMG,textile industry embraces sustainability innov...,Energy,Textile industry embraces sustainability inno...,"['textile', 'textiles', 'renewables', 'industr...",2
26,Agentic AI in the human capital management (HC...,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,2025-03-27,PWC,agentic ai human capital management hcm indust...,Technology,agentic ai human capital management hcm indus...,"['agents', 'agent', 'agentrecommends', 'agenth...",5
27,Indian family offices – the new investors for ...,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – \nthe new investors fo...,2025-03-26,PWC,indian family offices – new investors india ’ ...,Finance,indian family offices – new investors india ’...,"['families', 'investments', 'invest', 'investm...",3
28,Intergenerational trust: The key to succession...,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: \nThe key to success...,2025-03-11,PWC,intergenerational trust key succession family ...,Finance,Intergenerational trust key succession key su...,"['intergenerational', 'generations', 'generati...",1
29,Understanding the impact of GenAI on the India...,https://www.pwc.in/ghost-templates/understandi...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10,PWC,march indian healthcare ecosystem understandin...,Technology,genai could revolutionise healthcare unpreced...,"['transformingfuturehealthcareindia', 'genai',...",4
30,Quality measures and standards for transitioni...,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards \nMarch 2025\nf...,2025-03-07,PWC,quality measures standards march transitioning...,Healthcare,quality measures standards march transitionin...,"['healthcare', 'qualitycare', 'healthcarevbhc'...",4
31,The mutual funds route to Viksit Bharat @2047,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05,PWC,mutual funds route viksit bharat table content...,Finance,mutual funds route viksit bharat table conten...,"['investments', 'invest', 'investable', 'finan...",3
32,Financial health: Transcending from access to ...,https://www.pwc.in/ghost-templates/financial-h...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04,PWC,tm march financial health transcending access ...,Finance,Recent years india witnessed significant chan...,"['reliance', 'managementfinancial', 'financial...",3
33,Towards a climate-resilient future: Strategies...,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04,PWC,towards climateresilient future strategies and...,Policy,towards climateresilient future strategies an...,['climateandlanduserelateoneanotherqtnewsscien...,5

In [4]:
print(df.columns)      # See available columns

Index(['title', 'link', 'content', 'date', 'source', 'clean_content', 'domain',
       'summary', 'keywords', 'cluster'],
      dtype='object')

In [5]:
print(df.info())       # Check data types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          34 non-null     object
 1   link           34 non-null     object
 2   content        34 non-null     object
 3   date           34 non-null     object
 4   source         34 non-null     object
 5   clean_content  34 non-null     object
 6   domain         34 non-null     object
 7   summary        34 non-null     object
 8   keywords       34 non-null     object
 9   cluster        34 non-null     int64
dtypes: int64(1), object(9)
memory usage: 2.8+ KB
None

In [6]:
df.head(5)

,title,link,content,date,source,clean_content,domain,summary,keywords,cluster
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,2025-03-01 00:00:00,KPMG,india cx report commercial real estate close c...,Energy,Back industries aerospace defence space energ...,"['leasing', 'redevelopment', 'renovations', 'w...",2
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,2025-03-01 00:00:00,KPMG,india cx report residential real estate close ...,Energy,Back industries aerospace defence space energ...,"['residential', 'amenities', 'luxury', 'builde...",2
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,2025-03-01 00:00:00,KPMG,india cx report real estate close contactmail ...,Technology,Back industries aerospace defence space energ...,"['innovate', 'renewables', 'industries', 'expl...",2
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,2025-03-01 00:00:00,KPMG,india cx report premium hotels close contactma...,Energy,Back industries aerospace defence space energ...,"['hotels', 'hotel', 'hotelchain', 'resorts', '...",2
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,2025-03-01 00:00:00,KPMG,india cx report hotels close contactmail conta...,Technology,Back industries aerospace defence space energ...,"['hoteliers', 'hotels', 'hotel', 'establishmen...",2

In [7]:
df['source'].value_counts()

source
KPMG    26
PWC      8
Name: count, dtype: int64